name: bloc_gps_workshop
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  geolocator: ^11.0.0
  hydrated_bloc: ^9.1.3
  path_provider: ^2.1.2
  equatable: ^2.0.5
  flutter_map: ^6.1.0
  latlong2: ^0.9.0 # Required for coordinates

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/mock_routes/
